// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iTender.Integrator.Infrastructure.Persistence;

#nullable disable

namespace iTender.Integrator.Infrastructure.Migrations
{
    [DbContext(typeof(ItenderIntegratorDbContext))]
    [Migration("20260915082340_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Awards", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwardExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateSigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AwardExternalId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.ContractMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateMet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractMilestones", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRenewal")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("Lots", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComplianceStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastComplianceCheckUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationScheme")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ocid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("LastSyncedAtUtc");

                    b.HasIndex("Ocid", "ReleaseId")
                        .IsUnique();

                    b.ToTable("Releases", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalProcurementCategories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdditionalProcurementCategories");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeliveryLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EligibilityCriteria")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MainProcurementCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcurementMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcurementMethodDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProcuringEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProcuringEntityName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("ReleaseId")
                        .IsUnique()
                        .HasFilter("[ReleaseId] IS NOT NULL");

                    b.ToTable("Tenders", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.TenderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("TenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderDocument");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.TenderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("TenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderItems", (string)null);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Award", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Release", null)
                        .WithMany("Awards")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("AwardId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Value_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Value_Currency");

                            b1.HasKey("AwardId");

                            b1.ToTable("Awards");

                            b1.WithOwner()
                                .HasForeignKey("AwardId");
                        });

                    b.OwnsMany("iTender.Integrator.Domain.ValueObjects.AwardSupplier", "Suppliers", b1 =>
                        {
                            b1.Property<Guid>("AwardId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ExternalId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("AwardId", "Id");

                            b1.ToTable("AwardSuppliers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardId");
                        });

                    b.Navigation("Suppliers");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Contract", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Release", null)
                        .WithMany("Contracts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DurationInDays")
                                .HasColumnType("int")
                                .HasColumnName("Period_DurationInDays");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Period_EndDate");

                            b1.Property<DateTime?>("MaxExtentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Period_MaxExtentDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Period_StartDate");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Value_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Value_Currency");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsMany("iTender.Integrator.Domain.ValueObjects.ContractTransaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("PayeeId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("PayerId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("ContractId", "Id");

                            b1.ToTable("ContractTransactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");

                            b1.OwnsOne("iTender.Integrator.Domain.ValueObjects.Money", "Value", b2 =>
                                {
                                    b2.Property<Guid>("ContractTransactionContractId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ContractTransactionId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Value_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Value_Currency");

                                    b2.HasKey("ContractTransactionContractId", "ContractTransactionId");

                                    b2.ToTable("ContractTransactions");

                                    b2.WithOwner()
                                        .HasForeignKey("ContractTransactionContractId", "ContractTransactionId");
                                });

                            b1.Navigation("Value");
                        });

                    b.Navigation("Period");

                    b.Navigation("Transactions");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.ContractMilestone", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Contract", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Lot", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Tender", null)
                        .WithMany("Lots")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.DateRange", "ContractPeriod", b1 =>
                        {
                            b1.Property<Guid>("LotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DurationInDays")
                                .HasColumnType("int")
                                .HasColumnName("ContractPeriod_DurationInDays");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("ContractPeriod_EndDate");

                            b1.Property<DateTime?>("MaxExtentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("ContractPeriod_MaxExtentDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("ContractPeriod_StartDate");

                            b1.HasKey("LotId");

                            b1.ToTable("Lots");

                            b1.WithOwner()
                                .HasForeignKey("LotId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("LotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Value_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Value_Currency");

                            b1.HasKey("LotId");

                            b1.ToTable("Lots");

                            b1.WithOwner()
                                .HasForeignKey("LotId");
                        });

                    b.Navigation("ContractPeriod");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Party", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Release", null)
                        .WithMany("Parties")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.ContactPoint", "ContactPoint", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContactPoint_Email");

                            b1.Property<string>("FaxNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContactPoint_FaxNumber");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContactPoint_Name");

                            b1.Property<string>("Telephone")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContactPoint_Telephone");

                            b1.Property<string>("Url")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ContactPoint_Url");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_CountryName");

                            b1.Property<string>("Locality")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Locality");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Region")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Region");

                            b1.Property<string>("StreetAddress")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Address_StreetAddress");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("ContactPoint");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Tender", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Release", null)
                        .WithOne("Tender")
                        .HasForeignKey("iTender.Integrator.Domain.Entities.Tender", "ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.DateRange", "AwardPeriod", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DurationInDays")
                                .HasColumnType("int")
                                .HasColumnName("AwardPeriod_DurationInDays");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("AwardPeriod_EndDate");

                            b1.Property<DateTime?>("MaxExtentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("AwardPeriod_MaxExtentDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("AwardPeriod_StartDate");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Classification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Classification_Code");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Classification_Description");

                            b1.Property<string>("Scheme")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Classification_Scheme");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.ContactPoint", "ContactPerson", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContactPerson_Email");

                            b1.Property<string>("FaxNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContactPerson_FaxNumber");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContactPerson_Name");

                            b1.Property<string>("Telephone")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContactPerson_Telephone");

                            b1.Property<string>("Url")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ContactPerson_Url");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.DateRange", "EnquiryPeriod", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DurationInDays")
                                .HasColumnType("int")
                                .HasColumnName("EnquiryPeriod_DurationInDays");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EnquiryPeriod_EndDate");

                            b1.Property<DateTime?>("MaxExtentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EnquiryPeriod_MaxExtentDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EnquiryPeriod_StartDate");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.DateRange", "TenderPeriod", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("DurationInDays")
                                .HasColumnType("int")
                                .HasColumnName("TenderPeriod_DurationInDays");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("TenderPeriod_EndDate");

                            b1.Property<DateTime?>("MaxExtentDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("TenderPeriod_MaxExtentDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("TenderPeriod_StartDate");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Value_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Value_Currency");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.BriefingSession", "BriefingSession", b1 =>
                        {
                            b1.Property<Guid>("TenderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Compulsory")
                                .HasColumnType("bit")
                                .HasColumnName("BriefingSession_Compulsory");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("BriefingSession_Date");

                            b1.Property<bool>("IsSession")
                                .HasColumnType("bit")
                                .HasColumnName("BriefingSession_IsSession");

                            b1.Property<string>("Venue")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("BriefingSession_Venue");

                            b1.HasKey("TenderId");

                            b1.ToTable("Tenders");

                            b1.WithOwner()
                                .HasForeignKey("TenderId");
                        });

                    b.Navigation("AwardPeriod");

                    b.Navigation("BriefingSession");

                    b.Navigation("Classification");

                    b.Navigation("ContactPerson");

                    b.Navigation("EnquiryPeriod");

                    b.Navigation("TenderPeriod");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.TenderDocument", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Contract", null)
                        .WithMany("Documents")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("iTender.Integrator.Domain.Entities.Tender", null)
                        .WithMany("Documents")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.TenderItem", b =>
                {
                    b.HasOne("iTender.Integrator.Domain.Entities.Tender", null)
                        .WithMany("Items")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("iTender.Integrator.Domain.ValueObjects.Classification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("TenderItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Classification_Code");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Classification_Description");

                            b1.Property<string>("Scheme")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Classification_Scheme");

                            b1.HasKey("TenderItemId");

                            b1.ToTable("TenderItems");

                            b1.WithOwner()
                                .HasForeignKey("TenderItemId");
                        });

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Release", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Contracts");

                    b.Navigation("Parties");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("iTender.Integrator.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Items");

                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
